# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    assignees:
      - "Charismara"
    commit-message:
      prefix: "[Update]"
    target-branch: "master"
registries:
  manasmods:
    type: maven-repository
    url: https://manasmods.bytesafe.dev/maven/manasmods
    username: ${{secrets.MANAS_MAVEN_USER}}
    password: ${{secrets.MANAS_MAVEN_PASSWORD}}
