modLoader="javafml"
loaderVersion="${forgeLoaderVersion}"
license="All rights reserved"
[[mods]]
modId="unordinary_basics"
version="${modVersion}"
displayName="Unordinary Basics"
logoFile="logo.png"

#credits="Something here" #optional

authors="ManasMods"

description='''
This mod is designed to enchance the vanilla experience. First adding slabs and stairs of most blocks then QoL changes such as changes to crafting recipes.
'''

[[dependencies.unordinary_basics]]
    modId="forge"
    mandatory=true
    versionRange="${forgeLoaderVersion}"
    ordering="NONE"
    side="BOTH"
[[dependencies.unordinary_basics]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionCheck}"
    ordering="NONE"
    side="BOTH"
[[dependencies.unordinary_basics]]
    modId="manascore"
    mandatory=true
    versionRange="${manasVersionCheck}"
    ordering="NONE"
    side="BOTH"
[[dependencies.unordinary_basics]]
    modId="patchouli"
    mandatory=false
    versionRange="${patchouliVersionCheck}"
    ordering="NONE"
    side="BOTH"