name: Bug Report
description: >-
  Please use this template when you have encountered a bug in Unordinary Basics
  If the issue seems to affect only one mod, please report to them first instead of here.
title: '[Bug]: '
labels:
  - "Bug"
  - "Triage"
body:
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - 1.18.2
    validations:
      required: true
  - type: input
    id: manascore-version
    attributes:
      label: ManasCore Version
      description: What version of ManasCore are you running?
      placeholder: ex. 0.0.0.14
    validations:
      required: true
  - type: input
    id: unordinarybasics-version
    attributes:
      label: Unordinary Basics Version
      description: What version of Unordinary Basics are you running?
      placeholder: ex. 1.0.0.0
    validations:
      required: true
  - type: textarea
    id: repro_steps
    validations:
      required: true
    attributes:
      label: Steps to Reproduce the Bug
      description: Please explain what we need to do to cause the bug.
      placeholder: >-
        Example:

        1. Install Mod X
        2. Start Game
        3. Place Block X
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: >-
        Please explain what should happen when you follow the steps, if the bug
        were fixed.
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: >-
        Please briefly explain what actually happens when you follow the steps,
        because of the bug.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Extra Notes (Optional)
      description: >-
        Optionally, please include anything else you'd like to say about the bug.
    validations:
      required: false
  - type: markdown
    attributes:
      value: >-
        ## Sharing your `latest.log`

        In order to diagnose a bug, we will need to see your `latest.log`.

        To share your `latest.log` here, please follow these steps:


        1. If you don't have it already, find your `latest.log` file.

        a. [Find your minecraft
        folder](https://stickypiston.co/account/knowledgebase/130/How-do-I-find-my-Minecraft-Folder.html)

        b. In the minecraft folder, go into the `logs` folder and find the
        `latest.log` file.

        1. Create a Gist from the `latest.log`, and copy the url.

        [Click here for instructions on creating a
        Gist](https://gist.github.com/mezz/c3f0931344d81afd366e0d85a8ed1031)
  - type: input
    id: crashlog
    attributes:
      label: latest.log
      description: Please paste the url to the gist containing your `latest.log` file.
      placeholder: https://gist.github.com/<your_user_name>/<gist_id>