name: Feature Request
description: >-
  Please use this template when you want to suggest a feature for Unordinary Basics.
title: '[Feature Request]: '
labels:
  - "Feature Request"
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      placeholder: >-
        Please describe your feature as clear as possible.
    validations:
      required: true